/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as TTokenRouteImport } from './routes/t.$token'
import { Route as AppUsersRouteImport } from './routes/app.users'
import { Route as AppSuppliersRouteImport } from './routes/app.suppliers'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppSellRouteImport } from './routes/app.sell'
import { Route as AppScheduleRouteImport } from './routes/app.schedule'
import { Route as AppReportsRouteImport } from './routes/app.reports'
import { Route as AppPayrollRouteImport } from './routes/app.payroll'
import { Route as AppInventoryRouteImport } from './routes/app.inventory'
import { Route as AppHrRouteImport } from './routes/app.hr'
import { Route as AppFinanceRouteImport } from './routes/app.finance'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppCommissionsRouteImport } from './routes/app.commissions'
import { Route as AppCashRouteImport } from './routes/app.cash'
import { Route as AppInventoryProductIdRouteImport } from './routes/app.inventory.$productId'
import { Route as AppHrEmployeeIdRouteImport } from './routes/app.hr.$employeeId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const TTokenRoute = TTokenRouteImport.update({
  id: '/t/$token',
  path: '/t/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppSuppliersRoute = AppSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSellRoute = AppSellRouteImport.update({
  id: '/sell',
  path: '/sell',
  getParentRoute: () => AppRoute,
} as any)
const AppScheduleRoute = AppScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppPayrollRoute = AppPayrollRouteImport.update({
  id: '/payroll',
  path: '/payroll',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryRoute = AppInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AppRoute,
} as any)
const AppHrRoute = AppHrRouteImport.update({
  id: '/hr',
  path: '/hr',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceRoute = AppFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCommissionsRoute = AppCommissionsRouteImport.update({
  id: '/commissions',
  path: '/commissions',
  getParentRoute: () => AppRoute,
} as any)
const AppCashRoute = AppCashRouteImport.update({
  id: '/cash',
  path: '/cash',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryProductIdRoute = AppInventoryProductIdRouteImport.update({
  id: '/$productId',
  path: '/$productId',
  getParentRoute: () => AppInventoryRoute,
} as any)
const AppHrEmployeeIdRoute = AppHrEmployeeIdRouteImport.update({
  id: '/$employeeId',
  path: '/$employeeId',
  getParentRoute: () => AppHrRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/cash': typeof AppCashRoute
  '/app/commissions': typeof AppCommissionsRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/finance': typeof AppFinanceRoute
  '/app/hr': typeof AppHrRouteWithChildren
  '/app/inventory': typeof AppInventoryRouteWithChildren
  '/app/payroll': typeof AppPayrollRoute
  '/app/reports': typeof AppReportsRoute
  '/app/schedule': typeof AppScheduleRoute
  '/app/sell': typeof AppSellRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/suppliers': typeof AppSuppliersRoute
  '/app/users': typeof AppUsersRoute
  '/t/$token': typeof TTokenRoute
  '/app/': typeof AppIndexRoute
  '/app/hr/$employeeId': typeof AppHrEmployeeIdRoute
  '/app/inventory/$productId': typeof AppInventoryProductIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app/cash': typeof AppCashRoute
  '/app/commissions': typeof AppCommissionsRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/finance': typeof AppFinanceRoute
  '/app/hr': typeof AppHrRouteWithChildren
  '/app/inventory': typeof AppInventoryRouteWithChildren
  '/app/payroll': typeof AppPayrollRoute
  '/app/reports': typeof AppReportsRoute
  '/app/schedule': typeof AppScheduleRoute
  '/app/sell': typeof AppSellRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/suppliers': typeof AppSuppliersRoute
  '/app/users': typeof AppUsersRoute
  '/t/$token': typeof TTokenRoute
  '/app': typeof AppIndexRoute
  '/app/hr/$employeeId': typeof AppHrEmployeeIdRoute
  '/app/inventory/$productId': typeof AppInventoryProductIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/cash': typeof AppCashRoute
  '/app/commissions': typeof AppCommissionsRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/finance': typeof AppFinanceRoute
  '/app/hr': typeof AppHrRouteWithChildren
  '/app/inventory': typeof AppInventoryRouteWithChildren
  '/app/payroll': typeof AppPayrollRoute
  '/app/reports': typeof AppReportsRoute
  '/app/schedule': typeof AppScheduleRoute
  '/app/sell': typeof AppSellRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/suppliers': typeof AppSuppliersRoute
  '/app/users': typeof AppUsersRoute
  '/t/$token': typeof TTokenRoute
  '/app/': typeof AppIndexRoute
  '/app/hr/$employeeId': typeof AppHrEmployeeIdRoute
  '/app/inventory/$productId': typeof AppInventoryProductIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/app/cash'
    | '/app/commissions'
    | '/app/dashboard'
    | '/app/finance'
    | '/app/hr'
    | '/app/inventory'
    | '/app/payroll'
    | '/app/reports'
    | '/app/schedule'
    | '/app/sell'
    | '/app/settings'
    | '/app/suppliers'
    | '/app/users'
    | '/t/$token'
    | '/app/'
    | '/app/hr/$employeeId'
    | '/app/inventory/$productId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/app/cash'
    | '/app/commissions'
    | '/app/dashboard'
    | '/app/finance'
    | '/app/hr'
    | '/app/inventory'
    | '/app/payroll'
    | '/app/reports'
    | '/app/schedule'
    | '/app/sell'
    | '/app/settings'
    | '/app/suppliers'
    | '/app/users'
    | '/t/$token'
    | '/app'
    | '/app/hr/$employeeId'
    | '/app/inventory/$productId'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/app/cash'
    | '/app/commissions'
    | '/app/dashboard'
    | '/app/finance'
    | '/app/hr'
    | '/app/inventory'
    | '/app/payroll'
    | '/app/reports'
    | '/app/schedule'
    | '/app/sell'
    | '/app/settings'
    | '/app/suppliers'
    | '/app/users'
    | '/t/$token'
    | '/app/'
    | '/app/hr/$employeeId'
    | '/app/inventory/$productId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  TTokenRoute: typeof TTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/t/$token': {
      id: '/t/$token'
      path: '/t/$token'
      fullPath: '/t/$token'
      preLoaderRoute: typeof TTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/users': {
      id: '/app/users'
      path: '/users'
      fullPath: '/app/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/suppliers': {
      id: '/app/suppliers'
      path: '/suppliers'
      fullPath: '/app/suppliers'
      preLoaderRoute: typeof AppSuppliersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/sell': {
      id: '/app/sell'
      path: '/sell'
      fullPath: '/app/sell'
      preLoaderRoute: typeof AppSellRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/schedule': {
      id: '/app/schedule'
      path: '/schedule'
      fullPath: '/app/schedule'
      preLoaderRoute: typeof AppScheduleRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/payroll': {
      id: '/app/payroll'
      path: '/payroll'
      fullPath: '/app/payroll'
      preLoaderRoute: typeof AppPayrollRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/inventory': {
      id: '/app/inventory'
      path: '/inventory'
      fullPath: '/app/inventory'
      preLoaderRoute: typeof AppInventoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/hr': {
      id: '/app/hr'
      path: '/hr'
      fullPath: '/app/hr'
      preLoaderRoute: typeof AppHrRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/finance': {
      id: '/app/finance'
      path: '/finance'
      fullPath: '/app/finance'
      preLoaderRoute: typeof AppFinanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/commissions': {
      id: '/app/commissions'
      path: '/commissions'
      fullPath: '/app/commissions'
      preLoaderRoute: typeof AppCommissionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/cash': {
      id: '/app/cash'
      path: '/cash'
      fullPath: '/app/cash'
      preLoaderRoute: typeof AppCashRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/inventory/$productId': {
      id: '/app/inventory/$productId'
      path: '/$productId'
      fullPath: '/app/inventory/$productId'
      preLoaderRoute: typeof AppInventoryProductIdRouteImport
      parentRoute: typeof AppInventoryRoute
    }
    '/app/hr/$employeeId': {
      id: '/app/hr/$employeeId'
      path: '/$employeeId'
      fullPath: '/app/hr/$employeeId'
      preLoaderRoute: typeof AppHrEmployeeIdRouteImport
      parentRoute: typeof AppHrRoute
    }
  }
}

interface AppHrRouteChildren {
  AppHrEmployeeIdRoute: typeof AppHrEmployeeIdRoute
}

const AppHrRouteChildren: AppHrRouteChildren = {
  AppHrEmployeeIdRoute: AppHrEmployeeIdRoute,
}

const AppHrRouteWithChildren = AppHrRoute._addFileChildren(AppHrRouteChildren)

interface AppInventoryRouteChildren {
  AppInventoryProductIdRoute: typeof AppInventoryProductIdRoute
}

const AppInventoryRouteChildren: AppInventoryRouteChildren = {
  AppInventoryProductIdRoute: AppInventoryProductIdRoute,
}

const AppInventoryRouteWithChildren = AppInventoryRoute._addFileChildren(
  AppInventoryRouteChildren,
)

interface AppRouteChildren {
  AppCashRoute: typeof AppCashRoute
  AppCommissionsRoute: typeof AppCommissionsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppFinanceRoute: typeof AppFinanceRoute
  AppHrRoute: typeof AppHrRouteWithChildren
  AppInventoryRoute: typeof AppInventoryRouteWithChildren
  AppPayrollRoute: typeof AppPayrollRoute
  AppReportsRoute: typeof AppReportsRoute
  AppScheduleRoute: typeof AppScheduleRoute
  AppSellRoute: typeof AppSellRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSuppliersRoute: typeof AppSuppliersRoute
  AppUsersRoute: typeof AppUsersRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCashRoute: AppCashRoute,
  AppCommissionsRoute: AppCommissionsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppFinanceRoute: AppFinanceRoute,
  AppHrRoute: AppHrRouteWithChildren,
  AppInventoryRoute: AppInventoryRouteWithChildren,
  AppPayrollRoute: AppPayrollRoute,
  AppReportsRoute: AppReportsRoute,
  AppScheduleRoute: AppScheduleRoute,
  AppSellRoute: AppSellRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSuppliersRoute: AppSuppliersRoute,
  AppUsersRoute: AppUsersRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  TTokenRoute: TTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
